import { NextRequest, NextResponse } from 'next/server';
import { MobileMoneyParser } from '@/lib/parsers';
import { processedStatements } from '../../process/[uploadId]/route';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ uploadId: string }> }
) {
  const { uploadId } = await params;
  const { searchParams } = new URL(request.url);
  const format = searchParams.get('format') || 'csv';

  try {
    // Get processed statement data
    const processedData = processedStatements.get(uploadId);
    if (!processedData) {
      return NextResponse.json(
        { error: 'Processed data not found. Please upload and process the file first.' },
        { status: 404 }
      );
    }

    if (format === 'csv') {
      // Generate CSV content
      const csvContent = MobileMoneyParser.generateCSV({
        provider: processedData.provider,
        accountNumber: processedData.accountNumber,
        period: processedData.period,
        openingBalance: processedData.openingBalance,
        closingBalance: processedData.closingBalance,
        transactions: processedData.transactions,
        totalTransactions: processedData.totalTransactions
      });

      // Create filename with timestamp and provider
      const timestamp = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
      const filename = `${processedData.provider}_MobileMoney_${processedData.accountNumber}_${timestamp}.csv`;

      // Return CSV file
      return new NextResponse(csvContent, {
        status: 200,
        headers: {
          'Content-Type': 'text/csv; charset=utf-8',
          'Content-Disposition': `attachment; filename="${filename}"`,
          'Cache-Control': 'no-cache, no-store, must-revalidate',
        },
      });
    }

    if (format === 'summary') {
      // Generate summary report
      const summary = processedData.summary;
      const summaryContent = generateSummaryReport(processedData, summary);
      
      const timestamp = new Date().toISOString().split('T')[0];
      const filename = `${processedData.provider}_Summary_${processedData.accountNumber}_${timestamp}.txt`;

      return new NextResponse(summaryContent, {
        status: 200,
        headers: {
          'Content-Type': 'text/plain; charset=utf-8',
          'Content-Disposition': `attachment; filename="${filename}"`,
          'Cache-Control': 'no-cache, no-store, must-revalidate',
        },
      });
    }

    return NextResponse.json(
      { error: 'Invalid format. Use "csv" or "summary"' },
      { status: 400 }
    );

  } catch (error) {
    console.error('Download error:', error);
    return NextResponse.json(
      { error: 'Download failed. Please try again.' },
      { status: 500 }
    );
  }
}

function generateSummaryReport(processedData: any, summary: any): string {
  const report = `
MOBILE MONEY STATEMENT SUMMARY
===============================

Account Information:
- Provider: ${processedData.provider}
- Account Number: ${processedData.accountNumber}
- Statement Period: ${processedData.period.from} to ${processedData.period.to}

Balance Information:
- Opening Balance: UGX ${processedData.openingBalance.toLocaleString()}
- Closing Balance: UGX ${processedData.closingBalance.toLocaleString()}
- Net Change: UGX ${(processedData.closingBalance - processedData.openingBalance).toLocaleString()}

Transaction Summary:
- Total Transactions: ${processedData.totalTransactions}

Money Sent:
- Count: ${summary.sent.count}
- Total Amount: UGX ${summary.sent.total.toLocaleString()}

Money Received:
- Count: ${summary.received.count}
- Total Amount: UGX ${summary.received.total.toLocaleString()}

Cash Withdrawals:
- Count: ${summary.withdrawals.count}
- Total Amount: UGX ${summary.withdrawals.total.toLocaleString()}

Cash Deposits:
- Count: ${summary.deposits.count}
- Total Amount: UGX ${summary.deposits.total.toLocaleString()}

Bill Payments:
- Count: ${summary.bills.count}
- Total Amount: UGX ${summary.bills.total.toLocaleString()}

Airtime Purchases:
- Count: ${summary.airtime.count}
- Total Amount: UGX ${summary.airtime.total.toLocaleString()}

Report Generated: ${new Date().toLocaleString()}
Generated by MoMo2CSV - https://github.com/gideon-tech/mobile-money-csv

===============================
`;

  return report.trim();
}